# Generated by Django 4.2.1 on 2023-05-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='mage',
            new_name='image',
        ),
    ]
